name: MoonDBC
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-moonbit@v1.22
      - run: moon version --all
      - run: moon fmt --check
      - run: moon check --deny-warn
      - run: moon test --deny-warn
      - run: moon build
      - run: moon info
